// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
