// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {events} from '../models';

export function CertReady():Promise<boolean>;

export function CertStatus():Promise<models.CertStatus>;

export function CopyAsCurl(arg1:models.HTTPPacket):Promise<events.Event>;

export function DefaultDecryptRule():Promise<string>;

export function DefaultRewriteRules():Promise<string>;

export function DisableProxy():Promise<events.Event>;

export function Download(arg1:models.HTTPPacket):Promise<events.Event>;

export function EnableProxy():Promise<events.Event>;

export function ExportHAR(arg1:Array<models.HTTPPacket>):Promise<events.Event>;

export function FireErrorEvent(arg1:number,arg2:string):Promise<void>;

export function FireEvent(arg1:number,arg2:string):Promise<void>;

export function GenerateCert():Promise<events.Event>;

export function GetConfig():Promise<models.Config>;

export function GetDataDir():Promise<string>;

export function GetDevices():Promise<Array<models.Device>>;

export function GetPendingBreakpoints():Promise<Array<models.BreakpointHit>>;

export function GetStatus():Promise<models.AppStatus>;

export function GetTCPStream(arg1:string):Promise<models.TCPStreamDetail>;

export function GetTCPStreams():Promise<Array<models.TCPStreamSummary>>;

export function InstallCert():Promise<events.Event>;

export function ReleaseAllBreakpoints():Promise<events.Event>;

export function Replay(arg1:models.ReplayRequest):Promise<events.Event>;

export function ResetTCPStreams():Promise<events.Event>;

export function ResolveBreakpoint(arg1:models.BreakpointResolution):Promise<events.Event>;

export function SaveBreakpointConfig(arg1:models.BreakpointConfig):Promise<events.Event>;

export function SaveDecryptRule(arg1:string):Promise<events.Event>;

export function SaveRewriteRules(arg1:string):Promise<events.Event>;

export function SaveTCPStreamConfig(arg1:models.TCPStreamConfig):Promise<events.Event>;

export function SaveWebSocketConfig(arg1:models.WebSocketConfig):Promise<events.Event>;

export function SetConfig(arg1:string,arg2:models.Config):Promise<void>;

export function StartIPCapture(arg1:string):Promise<void>;

export function StartProxy():Promise<events.Event>;

export function StopIPCapture():Promise<events.Event>;

export function StopProxy():Promise<events.Event>;

export function Test():Promise<string>;

export function UninstallCert():Promise<events.Event>;
