// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {events} from '../models';

export function CertReady():Promise<boolean>;

export function CertStatus():Promise<models.CertStatus>;

export function DisableProxy():Promise<events.Event>;

export function Download(arg1:models.HTTPPacket):Promise<events.Event>;

export function EnableProxy():Promise<events.Event>;

export function ExportHAR(arg1:Array<models.HTTPPacket>):Promise<events.Event>;

export function FireErrorEvent(arg1:number,arg2:string):Promise<void>;

export function FireEvent(arg1:number,arg2:string):Promise<void>;

export function GenerateCert():Promise<events.Event>;

export function GetConfig():Promise<models.Config>;

export function GetDataDir():Promise<string>;

export function GetDevices():Promise<Array<models.Device>>;

export function InstallCert():Promise<events.Event>;

export function Replay(arg1:models.ReplayRequest):Promise<events.Event>;

export function SetConfig(arg1:string,arg2:models.Config):Promise<void>;

export function StartIPCapture(arg1:string):Promise<void>;

export function StartProxy():Promise<events.Event>;

export function StopIPCapture():Promise<events.Event>;

export function StopProxy():Promise<events.Event>;

export function Test():Promise<string>;

export function UninstallCert():Promise<events.Event>;
