// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
