// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartProxy(arg1:number,arg2:boolean):Promise<void>;

export function StopProxy():Promise<void>;

export function Test():Promise<string>;
