// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CertReady() {
  return window['go']['main']['App']['CertReady']();
}

export function DisableProxy() {
  return window['go']['main']['App']['DisableProxy']();
}

export function EnableProxy() {
  return window['go']['main']['App']['EnableProxy']();
}

export function FireErrorEvent(arg1, arg2) {
  return window['go']['main']['App']['FireErrorEvent'](arg1, arg2);
}

export function FireEvent(arg1, arg2) {
  return window['go']['main']['App']['FireEvent'](arg1, arg2);
}

export function GenerateCert() {
  return window['go']['main']['App']['GenerateCert']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function StartIPCapture(arg1) {
  return window['go']['main']['App']['StartIPCapture'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopIPCapture() {
  return window['go']['main']['App']['StopIPCapture']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function Test() {
  return window['go']['main']['App']['Test']();
}

export function UninstallCert() {
  return window['go']['main']['App']['UninstallCert']();
}
